<?php
/**
 * Zend2 Framework
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://framework.zend.com/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   Zend2
 * @package    Zend2_Validator
 * @copyright  Copyright (c) 2005-2012 Zend2 Technologies USA Inc. (http://www.zend.com)
 * @license    http://framework.zend.com/license/new-bsd     New BSD License
 */

namespace Zend2\Validator;

use Zend2\Loader\PluginClassLoader;

/**
 * Plugin Class Loader implementation for validators.
 *
 * @category   Zend2
 * @package    Zend2_Validator
 * @copyright  Copyright (c) 2005-2012 Zend2 Technologies USA Inc. (http://www.zend.com)
 * @license    http://framework.zend.com/license/new-bsd     New BSD License
 */
class ValidatorLoader extends PluginClassLoader
{
    /**
     * @var array Pre-aliased filter 
     */
    protected $plugins = array(
        'alnum'                        => 'Zend2\Validator\Alnum',
        'alpha'                        => 'Zend2\Validator\Alpha',
        'barcode_code_25_interleaved'  => 'Zend2\Validator\Barcode\Code25interleaved',
        'barcode_code25_interleaved'   => 'Zend2\Validator\Barcode\Code25interleaved',
        'barcode\\code_25_interleaved' => 'Zend2\Validator\Barcode\Code25interleaved',
        'barcode\\code25_interleaved'  => 'Zend2\Validator\Barcode\Code25interleaved',
        'barcode_code_25'              => 'Zend2\Validator\Barcode\Code25',
        'barcode_code25'               => 'Zend2\Validator\Barcode\Code25',
        'barcode\\code_25'             => 'Zend2\Validator\Barcode\Code25',
        'barcode\\code25'              => 'Zend2\Validator\Barcode\Code25',
        'barcode_code_39_ext'          => 'Zend2\Validator\Barcode\Code39ext',
        'barcode_code39_ext'           => 'Zend2\Validator\Barcode\Code39ext',
        'barcode\\code_39_ext'         => 'Zend2\Validator\Barcode\Code39ext',
        'barcode\\code39_ext'          => 'Zend2\Validator\Barcode\Code39ext',
        'barcode_code_39'              => 'Zend2\Validator\Barcode\Code39',
        'barcode_code39'               => 'Zend2\Validator\Barcode\Code39',
        'barcode\\code_39'             => 'Zend2\Validator\Barcode\Code39',
        'barcode\\code39'              => 'Zend2\Validator\Barcode\Code39',
        'barcode_code_93_ext'          => 'Zend2\Validator\Barcode\Code93ext',
        'barcode_code93_ext'           => 'Zend2\Validator\Barcode\Code93ext',
        'barcode\\code_93_ext'         => 'Zend2\Validator\Barcode\Code93ext',
        'barcode\\code93_ext'          => 'Zend2\Validator\Barcode\Code93ext',
        'barcode_code_93'              => 'Zend2\Validator\Barcode\Code93',
        'barcode_code93'               => 'Zend2\Validator\Barcode\Code93',
        'barcode\\code_93'             => 'Zend2\Validator\Barcode\Code93',
        'barcode\\code93'              => 'Zend2\Validator\Barcode\Code93',
        'barcode_ean_12'               => 'Zend2\Validator\Barcode\Ean12',
        'barcode_ean12'                => 'Zend2\Validator\Barcode\Ean12',
        'barcode\\ean_12'              => 'Zend2\Validator\Barcode\Ean12',
        'barcode\\ean12'               => 'Zend2\Validator\Barcode\Ean12',
        'barcode_ean_13'               => 'Zend2\Validator\Barcode\Ean13',
        'barcode_ean13'                => 'Zend2\Validator\Barcode\Ean13',
        'barcode\\ean_13'              => 'Zend2\Validator\Barcode\Ean13',
        'barcode\\ean13'               => 'Zend2\Validator\Barcode\Ean13',
        'barcode_ean_14'               => 'Zend2\Validator\Barcode\Ean14',
        'barcode_ean14'                => 'Zend2\Validator\Barcode\Ean14',
        'barcode\\ean_14'              => 'Zend2\Validator\Barcode\Ean14',
        'barcode\\ean14'               => 'Zend2\Validator\Barcode\Ean14',
        'barcode_ean_18'               => 'Zend2\Validator\Barcode\Ean18',
        'barcode_ean18'                => 'Zend2\Validator\Barcode\Ean18',
        'barcode\\ean_18'              => 'Zend2\Validator\Barcode\Ean18',
        'barcode\\ean18'               => 'Zend2\Validator\Barcode\Ean18',
        'barcode_ean_2'                => 'Zend2\Validator\Barcode\Ean2',
        'barcode_ean2'                 => 'Zend2\Validator\Barcode\Ean2',
        'barcode\\ean_2'               => 'Zend2\Validator\Barcode\Ean2',
        'barcode\\ean2'                => 'Zend2\Validator\Barcode\Ean2',
        'barcode_ean_5'                => 'Zend2\Validator\Barcode\Ean5',
        'barcode_ean5'                 => 'Zend2\Validator\Barcode\Ean5',
        'barcode\\ean_5'               => 'Zend2\Validator\Barcode\Ean5',
        'barcode\\ean5'                => 'Zend2\Validator\Barcode\Ean5',
        'barcode_ean_8'                => 'Zend2\Validator\Barcode\Ean8',
        'barcode_ean8'                 => 'Zend2\Validator\Barcode\Ean8',
        'barcode\\ean_8'               => 'Zend2\Validator\Barcode\Ean8',
        'barcode\\ean8'                => 'Zend2\Validator\Barcode\Ean8',
        'barcode_gtin_12'              => 'Zend2\Validator\Barcode\Gtin12',
        'barcode_gtin12'               => 'Zend2\Validator\Barcode\Gtin12',
        'barcode\\gtin_12'             => 'Zend2\Validator\Barcode\Gtin12',
        'barcode\\gtin12'              => 'Zend2\Validator\Barcode\Gtin12',
        'barcode_gtin_13'              => 'Zend2\Validator\Barcode\Gtin13',
        'barcode_gtin13'               => 'Zend2\Validator\Barcode\Gtin13',
        'barcode\\gtin_13'             => 'Zend2\Validator\Barcode\Gtin13',
        'barcode\\gtin13'              => 'Zend2\Validator\Barcode\Gtin13',
        'barcode_gtin_14'              => 'Zend2\Validator\Barcode\Gtin14',
        'barcode_gtin14'               => 'Zend2\Validator\Barcode\Gtin14',
        'barcode\\gtin_14'             => 'Zend2\Validator\Barcode\Gtin14',
        'barcode\\gtin14'              => 'Zend2\Validator\Barcode\Gtin14',
        'barcode_ident_code'           => 'Zend2\Validator\Barcode\Identcode',
        'barcode_identcode'            => 'Zend2\Validator\Barcode\Identcode',
        'barcode\\ident_code'          => 'Zend2\Validator\Barcode\Identcode',
        'barcode\\identcode'           => 'Zend2\Validator\Barcode\Identcode',
        'barcode_intelligent_mail'     => 'Zend2\Validator\Barcode\Intelligentmail',
        'barcode_intelligentmail'      => 'Zend2\Validator\Barcode\Intelligentmail',
        'barcode\\intelligent_mail'    => 'Zend2\Validator\Barcode\Intelligentmail',
        'barcode\\intelligentmail'     => 'Zend2\Validator\Barcode\Intelligentmail',
        'barcode_issn'                 => 'Zend2\Validator\Barcode\Issn',
        'barcode\\issn'                => 'Zend2\Validator\Barcode\Issn',
        'barcode_itf_14'               => 'Zend2\Validator\Barcode\Itf14',
        'barcode_itf14'                => 'Zend2\Validator\Barcode\Itf14',
        'barcode\\itf_14'              => 'Zend2\Validator\Barcode\Itf14',
        'barcode\\itf14'               => 'Zend2\Validator\Barcode\Itf14',
        'barcode_leit_code'            => 'Zend2\Validator\Barcode\Leitcode',
        'barcode_leitcode'             => 'Zend2\Validator\Barcode\Leitcode',
        'barcode\\leit_code'           => 'Zend2\Validator\Barcode\Leitcode',
        'barcode\\leitcode'            => 'Zend2\Validator\Barcode\Leitcode',
        'barcode_planet'               => 'Zend2\Validator\Barcode\Planet',
        'barcode\\planet'              => 'Zend2\Validator\Barcode\Planet',
        'barcode_post_net'             => 'Zend2\Validator\Barcode\Postnet',
        'barcode_postnet'              => 'Zend2\Validator\Barcode\Postnet',
        'barcode\\post_net'            => 'Zend2\Validator\Barcode\Postnet',
        'barcode\\postnet'             => 'Zend2\Validator\Barcode\Postnet',
        'barcode_royal_mail'           => 'Zend2\Validator\Barcode\Royalmail',
        'barcode_royalmail'            => 'Zend2\Validator\Barcode\Royalmail',
        'barcode\\royal_mail'          => 'Zend2\Validator\Barcode\Royalmail',
        'barcode\\royalmail'           => 'Zend2\Validator\Barcode\Royalmail',
        'barcode_sscc'                 => 'Zend2\Validator\Barcode\Sscc',
        'barcode\\sscc'                => 'Zend2\Validator\Barcode\Sscc',
        'barcode_upca'                 => 'Zend2\Validator\Barcode\Upca',
        'barcode\\upca'                => 'Zend2\Validator\Barcode\Upca',
        'barcode_upce'                 => 'Zend2\Validator\Barcode\Upce',
        'barcode\\upce'                => 'Zend2\Validator\Barcode\Upce',
        'barcode'                      => 'Zend2\Validator\Barcode',
        'between'                      => 'Zend2\Validator\Between',
        'callback'                     => 'Zend2\Validator\Callback',
        'credit_card'                  => 'Zend2\Validator\CreditCard',
        'creditcard'                   => 'Zend2\Validator\CreditCard',
        'date'                         => 'Zend2\Validator\Date',
        'db_\\no_record_exists'        => 'Zend2\Validator\Db\NoRecordExists',
        'db_\\norecordexists'          => 'Zend2\Validator\Db\NoRecordExists',
        'db\\no_record_exists'         => 'Zend2\Validator\Db\NoRecordExists',
        'db\\norecordexists'           => 'Zend2\Validator\Db\NoRecordExists',
        'db_\\record_exists'           => 'Zend2\Validator\Db\RecordExists',
        'db_\\recordexists'            => 'Zend2\Validator\Db\RecordExists',
        'db\\record_exists'            => 'Zend2\Validator\Db\RecordExists',
        'db\\recordexists'             => 'Zend2\Validator\Db\RecordExists',
        'digits'                       => 'Zend2\Validator\Digits',
        'email_address'                => 'Zend2\Validator\EmailAddress',
        'emailaddress'                 => 'Zend2\Validator\EmailAddress',
        'file_count'                   => 'Zend2\Validator\File\Count',
        'file\\count'                  => 'Zend2\Validator\File\Count',
        'file_crc_32'                  => 'Zend2\Validator\File\Crc32',
        'file_crc32'                   => 'Zend2\Validator\File\Crc32',
        'file\\crc_32'                 => 'Zend2\Validator\File\Crc32',
        'file\\crc32'                  => 'Zend2\Validator\File\Crc32',
        'file_exclude_extension'       => 'Zend2\Validator\File\ExcludeExtension',
        'file_excludeextension'        => 'Zend2\Validator\File\ExcludeExtension',
        'file\\exclude_extension'      => 'Zend2\Validator\File\ExcludeExtension',
        'file\\excludeextension'       => 'Zend2\Validator\File\ExcludeExtension',
        'file_exclude_mime_type'       => 'Zend2\Validator\File\ExcludeMimeType',
        'file_exclude_mimetype'        => 'Zend2\Validator\File\ExcludeMimeType',
        'file_excludemimetype'         => 'Zend2\Validator\File\ExcludeMimeType',
        'file\\exclude_mime_type'      => 'Zend2\Validator\File\ExcludeMimeType',
        'file\\exclude_mimetype'       => 'Zend2\Validator\File\ExcludeMimeType',
        'file\\excludemimetype'        => 'Zend2\Validator\File\ExcludeMimeType',
        'file_exists'                  => 'Zend2\Validator\File\Exists',
        'file\\exists'                 => 'Zend2\Validator\File\Exists',
        'file_extension'               => 'Zend2\Validator\File\Extension',
        'file\\extension'              => 'Zend2\Validator\File\Extension',
        'file_files_size'              => 'Zend2\Validator\File\FilesSize',
        'file_filessize'               => 'Zend2\Validator\File\FilesSize',
        'file\\files_size'             => 'Zend2\Validator\File\FilesSize',
        'file\\filessize'              => 'Zend2\Validator\File\FilesSize',
        'file_hash'                    => 'Zend2\Validator\File\Hash',
        'file\\hash'                   => 'Zend2\Validator\File\Hash',
        'file_image_size'              => 'Zend2\Validator\File\ImageSize',
        'file_imagesize'               => 'Zend2\Validator\File\ImageSize',
        'file\\image_size'             => 'Zend2\Validator\File\ImageSize',
        'file\\imagesize'              => 'Zend2\Validator\File\ImageSize',
        'file_is_compressed'           => 'Zend2\Validator\File\IsCompressed',
        'file_iscompressed'            => 'Zend2\Validator\File\IsCompressed',
        'file\\is_compressed'          => 'Zend2\Validator\File\IsCompressed',
        'file\\iscompressed'           => 'Zend2\Validator\File\IsCompressed',
        'file_is_image'                => 'Zend2\Validator\File\IsImage',
        'file_isimage'                 => 'Zend2\Validator\File\IsImage',
        'file\\is_image'               => 'Zend2\Validator\File\IsImage',
        'file\\isimage'                => 'Zend2\Validator\File\IsImage',
        'file_md5'                     => 'Zend2\Validator\File\Md5',
        'file\\md5'                    => 'Zend2\Validator\File\Md5',
        'file_mime_type'               => 'Zend2\Validator\File\MimeType',
        'file_mimetype'                => 'Zend2\Validator\File\MimeType',
        'file\\mime_type'              => 'Zend2\Validator\File\MimeType',
        'file\\mimetype'               => 'Zend2\Validator\File\MimeType',
        'file_not_exists'              => 'Zend2\Validator\File\NotExists',
        'file_notexists'               => 'Zend2\Validator\File\NotExists',
        'file\\not_exists'             => 'Zend2\Validator\File\NotExists',
        'file\\notexists'              => 'Zend2\Validator\File\NotExists',
        'file_sha1'                    => 'Zend2\Validator\File\Sha1',
        'file\\sha1'                   => 'Zend2\Validator\File\Sha1',
        'file_size'                    => 'Zend2\Validator\File\Size',
        'file\\size'                   => 'Zend2\Validator\File\Size',
        'file_upload'                  => 'Zend2\Validator\File\Upload',
        'file\\upload'                 => 'Zend2\Validator\File\Upload',
        'file_word_count'              => 'Zend2\Validator\File\WordCount',
        'file_wordcount'               => 'Zend2\Validator\File\WordCount',
        'file\\word_count'             => 'Zend2\Validator\File\WordCount',
        'file\\wordcount'              => 'Zend2\Validator\File\WordCount',
        'float'                        => 'Zend2\Validator\Float',
        'greater_than'                 => 'Zend2\Validator\GreaterThan',
        'greaterthan'                  => 'Zend2\Validator\GreaterThan',
        'hex'                          => 'Zend2\Validator\Hex',
        'hostname'                     => 'Zend2\Validator\Hostname',
        'iban'                         => 'Zend2\Validator\Iban',
        'identical'                    => 'Zend2\Validator\Identical',
        'in_array'                     => 'Zend2\Validator\InArray',
        'inarray'                      => 'Zend2\Validator\InArray',
        'int'                          => 'Zend2\Validator\Int',
        'ip'                           => 'Zend2\Validator\Ip',
        'isbn'                         => 'Zend2\Validator\Isbn',
        'less_than'                    => 'Zend2\Validator\LessThan',
        'lessthan'                     => 'Zend2\Validator\LessThan',
        'not_empty'                    => 'Zend2\Validator\NotEmpty',
        'notempty'                     => 'Zend2\Validator\NotEmpty',
        'post_code'                    => 'Zend2\Validator\PostCode',
        'postcode'                     => 'Zend2\Validator\PostCode',
        'regex'                        => 'Zend2\Validator\Regex',
        'sitemap_change_freq'          => 'Zend2\Validator\Sitemap\Changefreq',
        'sitemap_changefreq'           => 'Zend2\Validator\Sitemap\Changefreq',
        'sitemap\\change_freq'         => 'Zend2\Validator\Sitemap\Changefreq',
        'sitemap\\changefreq'          => 'Zend2\Validator\Sitemap\Changefreq',
        'sitemap_last_mod'             => 'Zend2\Validator\Sitemap\Lastmod',
        'sitemap_lastmod'              => 'Zend2\Validator\Sitemap\Lastmod',
        'sitemap\\last_mod'            => 'Zend2\Validator\Sitemap\Lastmod',
        'sitemap\\lastmod'             => 'Zend2\Validator\Sitemap\Lastmod',
        'sitemap_loc'                  => 'Zend2\Validator\Sitemap\Loc',
        'sitemap\\loc'                 => 'Zend2\Validator\Sitemap\Loc',
        'sitemap_priority'             => 'Zend2\Validator\Sitemap\Priority',
        'sitemap\\priority'            => 'Zend2\Validator\Sitemap\Priority',
        'string_length'                => 'Zend2\Validator\StringLength',
        'stringlength'                 => 'Zend2\Validator\StringLength',
    );
}
